services:
  postgres:
    image: postgres:16-alpine
    container_name: hermex_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hermex
      POSTGRES_PASSWORD: hermex_secret
      POSTGRES_DB: hermex_dev
    ports:
      - "5432:5432"
    volumes:
      - hermex_postgres_data:/var/lib/postgresql/data

volumes:
  hermex_postgres_data:
    driver: local
